=== RUN   TestAddRoute
--- PASS: TestAddRoute (0.00s)
=== RUN   TestAddRouteFails
--- PASS: TestAddRouteFails (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.005s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/gin_test.go
TestName:  TestAddRoute
Import added at line: 7
Header added at line: 437
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/gin_test.go
Header added at line: 455
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/gin_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestAddRoute
--- PASS: TestAddRoute (0.10s)
=== RUN   TestAddRouteFails

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: HTTP method can not be empty

FAIL	github.com/gin-gonic/gin	0.110s
FAIL
