=== RUN   TestTreeChildConflict
--- PASS: TestTreeChildConflict (0.00s)
PASS
ok  	github.com/gin-gonic/gin	0.006s
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
TestName:  TestTreeChildConflict
Import added at line: 7
Header added at line: 438
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Projects/gin-master/tree_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestTreeChildConflict

Exit Replay with code  3 The program panicked unexpectedly
Exit Message: panic: ':othersub' in new path '/cmd/:tool/:othersub' conflicts with existing wildcard ':sub' in existing prefix '/cmd/:tool/:sub'

FAIL	github.com/gin-gonic/gin	0.109s
FAIL
