=== RUN   TestA04_CloseOnNil
--- FAIL: TestA04_CloseOnNil (0.00s)
panic: close of nil channel [recovered]
	panic: close of nil channel

goroutine 6 [running]:
testing.tRunner.func1.2({0x551040, 0x5b1410})
	/home/ilian/Tools/go-runtime/src/testing/testing.go:1734 +0x21c
testing.tRunner.func1()
	/home/ilian/Tools/go-runtime/src/testing/testing.go:1737 +0x35e
panic({0x551040?, 0x5b1410?})
	/home/ilian/Tools/go-runtime/src/runtime/panic.go:792 +0x132
scenarios.TestA04_CloseOnNil(0xc000003880?)
	/home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Own/Scenarios/scenarios_test.go:35 +0x15
testing.tRunner(0xc000003880, 0x585bd0)
	/home/ilian/Tools/go-runtime/src/testing/testing.go:1792 +0xf4
created by testing.(*T).Run in goroutine 1
	/home/ilian/Tools/go-runtime/src/testing/testing.go:1851 +0x413
FAIL	scenarios	0.004s
FAIL
FileName:  /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Own/Scenarios/scenarios_test.go
TestName:  TestA04_CloseOnNil
Import added at line: 3
Header added at line: 33
Header added at file: /home/ilian/Projects/Go_Fuzzing_Concurrency/Examples/Examples_Own/Scenarios/scenarios_test.go
go version go1.24.1 linux/amd64 ADVOCATE
=== RUN   TestA04_CloseOnNil

Exit Replay with code  33 Close on nil
Exit Message: panic: close of nil channel

FAIL	scenarios	0.104s
FAIL
